"use client";

import { useMemo, useState } from "react";
import {
  estimatedSpecRows,
  type DesignBrief,
} from "@/lib/design-brief";
import {
  assetUrl,
  type JobSnapshot,
  type StageState,
} from "@/lib/design-api";
import { DesignBriefResultsCollapsible } from "./DesignBriefResultsCollapsible";
import { StageProgress } from "./StageProgress";
import { TurntableViewer, type TurntableFrame } from "./TurntableViewer";
import { DesignImageZoom } from "./DesignImageZoom";

type ResultIcon =
  | "heart"
  | "share"
  | "download"
  | "copy"
  | "spec"
  | "hand"
  | "wand"
  | "rings"
  | "person";

const COMING_LATER_TOOLTIP = "Coming in a later release.";

export function DesignPackResults({
  brief,
  job,
  jobError,
  generating,
  stopping,
  onRegenerate,
  onImprove,
  onStartOver,
  onStopGeneration,
}: {
  brief: DesignBrief;
  job: JobSnapshot | null;
  jobError: Error | null;
  generating: boolean;
  stopping?: boolean;
  onRegenerate: () => void;
  onImprove: () => void;
  onStartOver: () => void;
  onStopGeneration: () => void;
}) {
  const [copied, setCopied] = useState(false);
  const [lightbox, setLightbox] = useState<{ url: string; label: string } | null>(null);

  const stages = job?.stages;
  const sketchStage = stages?.sketch;
  const heroStage = stages?.hero;
  const meshStage = stages?.mesh;
  const anglesStage = stages?.angles;
  const lightingStage = stages?.lighting;
  const specStage = stages?.spec;

  const designId = job?.design_id ?? "HM-2026-00000";
  const specRows = useMemo(() => {
    const fromJob = specStage?.spec_rows;
    if (fromJob && fromJob.length) return formatSpecRows(fromJob);
    return formatSpecRows(estimatedSpecRows(brief));
  }, [brief, specStage]);

  const heroUrl = heroStage?.asset_url ? assetUrl(heroStage.asset_url) : undefined;
  const meshGlbUrl =
    meshStage?.asset_url && meshStage.status === "done"
      ? assetUrl(meshStage.asset_url)
      : undefined;
  const tryOnHref =
    job?.job_id && heroStage?.asset_url && meshGlbUrl
      ? `/try-on?job_id=${encodeURIComponent(job.job_id)}`
      : null;
  const tryOnLockLabel =
    meshStage?.status === "running" || meshStage?.status === "pending"
      ? "Available once the 3D mesh finishes."
      : meshStage?.status === "failed"
        ? "3D mesh failed. Regenerate the pack to enable try-on."
        : "Available once the 3D mesh is ready.";
  const sketchUrl = sketchStage?.asset_url ? assetUrl(sketchStage.asset_url) : undefined;
  const turntableFrames: TurntableFrame[] = (anglesStage?.angle_urls ?? [])
    .map((a) => ({
      label: a.label,
      degrees: a.degrees ?? 0,
      url: assetUrl(a.url),
    }))
    .sort((a, b) => a.degrees - b.degrees);
  const lightingItems = (lightingStage?.lighting_urls ?? []).map((l) => ({
    label: l.label,
    url: assetUrl(l.url),
    tint: l.tint ?? "studio",
  }));

  const fatalError =
    job?.status === "failed"
      ? job.error_message ?? "Generation failed."
      : null;
  const isCancelled = job?.status === "cancelled";

  const copyId = async () => {
    try {
      await navigator.clipboard.writeText(designId);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* harmless */
    }
  };

  return (
    <div className="ds-results">
      <div className="ds-results-top">
        <div className="ds-results-head">
          <div className="ds-results-heading-copy">
            <h2 className="ds-results-title">
              {fatalError ? (
                <>
                  We hit a snag generating your <em>Design Pack</em>
                </>
              ) : isCancelled ? (
                <>
                  Generation <em>cancelled</em>
                </>
              ) : generating ? (
                <>
                  Your <em>AI Design Pack</em> is being prepared
                </>
              ) : (
                <>
                  Your <em>AI Design Pack</em> is ready
                </>
              )}
            </h2>
            <p>
              {fatalError
                ? "Try again, or edit your brief and submit a new design."
                : isCancelled
                  ? "No assets were saved. You can re-run from your current brief."
                  : generating
                    ? "We are generating each section one by one. You can watch the progress on each card."
                    : "Here is your complete custom ring design pack generated by our AI."}
            </p>
            {jobError && !fatalError && (
              <p className="ds-results-warning" role="status">
                Connection wobbled, retrying ({jobError.message}).
              </p>
            )}
          </div>

          <div className="ds-results-id-pill">
            <span>Design ID: {designId}</span>
            <button type="button" onClick={copyId} aria-label="Copy design ID">
              <ResultIcon type="copy" />
            </button>
            {copied && <small>Copied</small>}
          </div>

          <div className="ds-results-actions">
            <DisabledLaterButton icon="heart" label="Save Design" />
            <DisabledLaterButton icon="share" label="Share" />
            <DisabledLaterButton icon="download" label="Download Pack" primary />
          </div>
        </div>

      </div>

      <DesignBriefResultsCollapsible brief={brief} />

      {fatalError && (
        <div className="ds-results-banner ds-results-banner--error" role="alert">
          <div>
            <strong>Generation failed.</strong>
            <p>{fatalError}</p>
          </div>
          <div className="ds-results-banner-actions">
            <button type="button" className="btn-ghost" onClick={onImprove}>
              Edit brief
            </button>
            <button type="button" className="btn-primary" onClick={onRegenerate}>
              Try again
            </button>
          </div>
        </div>
      )}

      <div className="ds-results-layout">
        <main className="ds-results-main">
          <div className="ds-results-primary-grid">
            <ResultPanel
              number={1}
              title="Concept Sketch"
              action="View Full Size"
              src={sketchUrl}
              stage={sketchStage}
              progressLabel="Concept sketch"
              variant="sketch"
              showProgress={generating}
              onView={() =>
                sketchUrl && setLightbox({ url: sketchUrl, label: "Concept Sketch" })
              }
              onRetry={onRegenerate}
            />
            <ResultPanel
              number={2}
              title="Realistic Render"
              action="View Full Size"
              src={heroUrl}
              stage={heroStage}
              progressLabel="Realistic render"
              variant="render"
              showProgress={generating}
              onView={() =>
                heroUrl && setLightbox({ url: heroUrl, label: "Realistic Render" })
              }
              onRetry={onRegenerate}
            />
          </div>

          {anglesStage && anglesStage.status !== "skipped" && (
            <section className="ds-results-panel ds-results-panel--turntable">
              <PanelHeader
                number={3}
                title="Different angle views"
                meta={`(${turntableFrames.length || anglesStage.progress_total} views)`}
              />
              {meshStage &&
                meshStage.status !== "skipped" &&
                (meshStage.status === "running" || meshStage.status === "failed") && (
                <InlineStageProgress
                  stage={meshStage}
                  label="Research 3D mesh"
                  showCompleted={generating}
                />
              )}
              <InlineStageProgress
                stage={anglesStage}
                label="Different angle views"
                showCompleted={generating}
              />
              <StageBody stage={anglesStage} onRetry={onRegenerate}>
                <TurntableViewer
                  frames={turntableFrames}
                  loading={anglesStage.status === "running" && turntableFrames.length === 0}
                  expectedFrameCount={anglesStage.progress_total || 4}
                  meshGlbUrl={meshGlbUrl}
                  meshStatus={meshStage?.status}
                  meshPosterUrl={heroUrl}
                />
              </StageBody>
            </section>
          )}

          {lightingStage && lightingStage.status !== "skipped" && (
            <section className="ds-results-panel ds-results-panel--lighting">
              <PanelHeader
                number={4}
                title="Lighting Variations"
                meta={`(${lightingItems.length || lightingStage.progress_total} styles)`}
              />
              <InlineStageProgress
                stage={lightingStage}
                label="Lighting variations"
                showCompleted={generating}
              />
              <StageBody stage={lightingStage} onRetry={onRegenerate}>
                <div className="ds-results-light-row">
                  {lightingItems.map((light) => (
                    <LightingVariation
                      key={light.label}
                      label={light.label}
                      url={light.url}
                      tint={light.tint}
                      onViewFull={() =>
                        setLightbox({ url: light.url, label: light.label })
                      }
                    />
                  ))}
                </div>
              </StageBody>
            </section>
          )}
        </main>

        <aside className="ds-results-side">
          {specStage && specStage.status !== "skipped" && (
            <section className="ds-results-spec">
              <header className="ds-results-side-head">
                <ResultIcon type="spec" />
                <h3>AI Estimated Specifications</h3>
              </header>
              <InlineStageProgress
                stage={specStage}
                label="AI estimated specs"
                compact
                showCompleted={generating}
              />
              <ul className="ds-results-spec-list">
                {specRows.map((row, index) => (
                  <li
                    key={`${row.key}-${index}`}
                    className={index === 7 ? "ds-results-spec-divider" : ""}
                  >
                    <SpecIcon />
                    <span>{row.key}</span>
                    <strong>{row.value}</strong>
                  </li>
                ))}
              </ul>
              <p className="ds-results-spec-note">
                <InfoIcon /> These specifications are AI estimated, not exact manufacturing measurements.
              </p>
            </section>
          )}

          <section className="ds-results-next">
            <h3>What would you like to do next?</h3>
            <div className="ds-next-grid ds-next-grid--solo">
              {tryOnHref ? (
                <a
                  href={tryOnHref}
                  className="ds-next-card ds-next-card--enabled"
                >
                  <TryOnIcon />
                  <span className="ds-next-card-title">Try This Ring On</span>
                  <span className="ds-next-card-hint">
                    See it on your hand with live AR and a photoreal preview.
                  </span>
                  <span className="ds-next-card-arrow" aria-hidden>
                    →
                  </span>
                </a>
              ) : (
                <button
                  type="button"
                  className="ds-next-card"
                  disabled
                  aria-disabled="true"
                  title={tryOnLockLabel}
                >
                  <TryOnIcon />
                  <span className="ds-next-card-title">Try This Ring On</span>
                  <span className="ds-next-card-hint">
                    {tryOnLockLabel}
                  </span>
                  <span className="ds-next-card-arrow" aria-hidden>
                    →
                  </span>
                </button>
              )}
            </div>
          </section>
        </aside>
      </div>

      <section
        className="ds-results-start-over"
        aria-label={generating ? "Stop generation" : "Start a new design"}
      >
        {generating ? (
          <button
            type="button"
            className="btn-ghost ds-results-stop-cta"
            onClick={onStopGeneration}
            disabled={stopping}
          >
            <StopIcon />
            {stopping ? "Stopping…" : "Stop generation"}
          </button>
        ) : (
          <button type="button" className="ds-forest-cta" onClick={onStartOver}>
            Start new design
            <ForestCtaChevron />
          </button>
        )}
      </section>

      <div className="ds-results-footer-bar">
        <p>
          <LockIcon /> Starting a new design clears this session and removes generated files
          from the studio.
        </p>
        <div className="ds-results-footer-actions">
          <button
            type="button"
            className="ds-results-footer-btn"
            disabled
            aria-disabled="true"
            title={COMING_LATER_TOOLTIP}
          >
            Save to Collection
          </button>
          {generating ? (
            <button
              type="button"
              className="btn-ghost ds-results-footer-btn ds-results-footer-btn--stop"
              onClick={onStopGeneration}
              disabled={stopping}
            >
              <StopIcon />
              {stopping ? "Stopping…" : "Stop generation"}
            </button>
          ) : (
            <button type="button" className="ds-results-footer-btn" onClick={onStartOver}>
              Start New Design
            </button>
          )}
        </div>
      </div>

      {lightbox && (
        <div
          className="ds-lightbox"
          role="dialog"
          aria-modal
          aria-label={`Full size preview: ${lightbox.label}`}
          onClick={() => setLightbox(null)}
          onKeyDown={(e) => e.key === "Escape" && setLightbox(null)}
        >
          <figure className="ds-lightbox-figure" onClick={(e) => e.stopPropagation()}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={lightbox.url} alt={lightbox.label} />
            <figcaption>{lightbox.label}</figcaption>
          </figure>
          <button
            type="button"
            className="ds-lightbox-close"
            onClick={() => setLightbox(null)}
          >
            Close
          </button>
        </div>
      )}
    </div>
  );
}

function LightingVariation({
  label,
  url,
  tint,
  onViewFull,
}: {
  label: string;
  url: string;
  tint: string;
  onViewFull: () => void;
}) {
  return (
    <figure className={`ds-results-light ds-results-light--${tint}`}>
      <div className="ds-results-light-media">
        <DesignImageZoom
          src={url}
          alt={label}
          magnify={0.95}
          zoomPosition="original"
        />
      </div>
      <figcaption>{label}</figcaption>
      <button type="button" className="ds-results-light-view" onClick={onViewFull}>
        View full size
      </button>
    </figure>
  );
}

function ResultPanel({
  number,
  title,
  action,
  src,
  stage,
  progressLabel,
  variant,
  showProgress,
  onView,
  onRetry,
}: {
  number: number;
  title: string;
  action: string;
  src?: string;
  stage?: StageState;
  progressLabel: string;
  variant: "sketch" | "render";
  showProgress: boolean;
  onView: () => void;
  onRetry: () => void;
}) {
  const status = stage?.status ?? "pending";
  const loading = status === "pending" || status === "running";
  const failed = status === "failed";

  return (
    <section className={`ds-results-panel ds-results-panel--${variant}`}>
      <div className="ds-results-panel-head">
        <PanelHeader number={number} title={title} />
        <div className="ds-results-panel-actions">
          <button type="button" onClick={onView} disabled={!src}>
            {action}
          </button>
        </div>
      </div>
      <InlineStageProgress stage={stage} label={progressLabel} showCompleted={showProgress} />
      <div
        className={`ds-results-image ds-results-image--${variant} ds-results-image--paired ${
          loading ? "ds-results-image--loading" : ""
        } ${failed ? "ds-results-image--failed" : ""}`}
      >
        {src && !loading && !failed && (
          <DesignImageZoom
            src={src}
            alt={title}
            fit="contain"
            magnify={variant === "sketch" ? 1.05 : 1}
            zoomPosition="original"
          />
        )}
        {failed && (
          <div className="ds-results-image-failed-overlay">
            <p>
              <strong>This view did not generate.</strong>
            </p>
            <p>{stage?.error_message ?? "Engine reported an error."}</p>
            <button type="button" className="btn-ghost" onClick={onRetry}>
              Retry
            </button>
          </div>
        )}
      </div>
    </section>
  );
}

function InlineStageProgress({
  stage,
  label,
  compact,
  showCompleted,
}: {
  stage?: StageState;
  label: string;
  compact?: boolean;
  showCompleted?: boolean;
}) {
  if (!stage || stage.status === "skipped") return null;
  if (stage.status === "done" && !showCompleted) return null;
  return (
    <div className={`ds-inline-stage-progress ${compact ? "ds-inline-stage-progress--compact" : ""}`}>
      <StageProgress stage={stage} label={label} isNextUp={false} />
    </div>
  );
}

function StageBody({
  stage,
  children,
  onRetry,
}: {
  stage: StageState;
  children: React.ReactNode;
  onRetry: () => void;
}) {
  if (stage.status === "pending") {
    return (
      <p className="ds-results-stage-pending">
        Queued, will start shortly.
      </p>
    );
  }
  if (stage.status === "running") {
    return (
      <>
        {children}
      </>
    );
  }
  if (stage.status === "failed") {
    return (
      <div className="ds-results-stage-failed" role="alert">
        <p>{stage.error_message ?? "This stage failed."}</p>
        <button type="button" className="btn-ghost" onClick={onRetry}>
          Retry generation
        </button>
      </div>
    );
  }
  return <>{children}</>;
}

function PanelHeader({ number, title, meta }: { number: number; title: string; meta?: string }) {
  return (
    <h3 className="ds-results-panel-title">
      <span>{number}.</span> {title} {meta && <small>{meta}</small>}
    </h3>
  );
}

function DisabledLaterButton({
  icon,
  label,
  primary,
}: {
  icon: ResultIcon;
  label: string;
  primary?: boolean;
}) {
  return (
    <button
      type="button"
      className={`ds-results-action ${primary ? "ds-results-action--primary" : ""}`}
      disabled
      aria-disabled="true"
      title={COMING_LATER_TOOLTIP}
    >
      <ResultIcon type={icon} /> {label}
    </button>
  );
}

function formatSpecRows(rows: { key: string; value: string }[]) {
  const labelMap: Record<string, string> = {
    "Ring type": "Ring Type",
    Metal: "Metal",
    Setting: "Setting Style",
    "Centre stone": "Centre Stone",
    "Band style": "Band Style",
    Finish: "Finish",
    "Style mood": "Style Mood",
    "Extra details": "Extra Details",
    "Est. band width": "Estimated Band Width",
    "Est. setting height": "Estimated Setting Height",
    "Est. visual weight": "Visual Weight",
    "Design complexity": "Design Complexity",
    "Style direction": "Style Direction",
  };

  return rows.map((row) => ({ key: labelMap[row.key] ?? row.key, value: row.value }));
}

function ResultIcon({ type }: { type: ResultIcon }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" aria-hidden>
      {type === "heart" && <path d="M12 20s-7-4.4-9-9a4.3 4.3 0 017-4.7A4.3 4.3 0 0117 11c-2 4.6-5 9-5 9z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />}
      {type === "share" && <path d="M8 12l8-5M8 12l8 5M7 15a3 3 0 100-6 3 3 0 000 6zm10-6a3 3 0 100-6 3 3 0 000 6zm0 12a3 3 0 100-6 3 3 0 000 6z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />}
      {type === "download" && <path d="M12 4v10m0 0l-4-4m4 4l4-4M5 19h14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />}
      {type === "copy" && <path d="M8 8h10v12H8zM6 16H4V4h10v2" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" />}
      {type === "spec" && <path d="M7 4h7l3 3v13H7V4zm7 0v4h4M9 12h6M9 16h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />}
      {type === "hand" && <path d="M8 13V6a1.5 1.5 0 013 0v5M11 11V5a1.5 1.5 0 013 0v6M14 12V7a1.5 1.5 0 013 0v7c0 4-2.5 6-6 6H9c-2 0-3.5-1-4.5-3L3 14a1.7 1.7 0 013-1l2 3" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />}
      {type === "wand" && <path d="M5 19l10-10M13 3l1 3 3 1-3 1-1 3-1-3-3-1 3-1 1-3zM18 13l.7 2 2 .7-2 .7-.7 2-.7-2-2-.7 2-.7.7-2z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />}
      {type === "rings" && <path d="M9 14a5 5 0 100-10 5 5 0 000 10zm6 6a5 5 0 100-10 5 5 0 000 10z" stroke="currentColor" strokeWidth="1.5" />}
      {type === "person" && <path d="M12 12a4 4 0 100-8 4 4 0 000 8zm-7 8c1.2-4 3.5-6 7-6s5.8 2 7 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />}
    </svg>
  );
}

function SpecIcon() {
  return (
    <svg viewBox="0 0 18 18" fill="none" aria-hidden>
      <circle cx="9" cy="9" r="5.5" stroke="currentColor" strokeWidth="1.1" strokeDasharray="2 2" />
    </svg>
  );
}

function InfoIcon() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden>
      <circle cx="8" cy="8" r="6" stroke="currentColor" strokeWidth="1.2" />
      <path d="M8 7.5v3.5M8 5h.01" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
    </svg>
  );
}

function LockIcon() {
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden>
      <rect x="3" y="7" width="10" height="7" rx="1" stroke="currentColor" strokeWidth="1.1" />
      <path d="M5.5 7V5a2.5 2.5 0 015 0v2" stroke="currentColor" strokeWidth="1.1" />
    </svg>
  );
}

function TryOnIcon() {
  return (
    <svg viewBox="0 0 24 24" className="ds-next-card-icon" fill="none" aria-hidden>
      <path
        d="M8 13V6a1.5 1.5 0 013 0v5M11 11V5a1.5 1.5 0 013 0v6M14 12V7a1.5 1.5 0 013 0v7c0 4-2.5 6-6 6H9c-2 0-3.5-1-4.5-3L3 14a1.7 1.7 0 013-1l2 3"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ForestCtaChevron() {
  return (
    <svg viewBox="0 0 20 20" className="ds-forest-cta__chevron" fill="none" aria-hidden>
      <path
        d="M8 5l5 5-5 5"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function StopIcon() {
  return (
    <svg viewBox="0 0 16 16" className="ds-stop-cta-icon" fill="none" aria-hidden>
      <rect x="4" y="4" width="8" height="8" fill="currentColor" />
    </svg>
  );
}
