/**
 * Three.js scene for live AR ring overlay.
 *
 * Drives a textured GLB ring (generated by /design via Meshy / Tripo) on
 * top of a webcam frame. The scene is a thin wrapper around a perspective
 * camera whose frustum matches the on-screen video element, so MediaPipe
 * landmarks (which are in normalised video coordinates) can be mapped to
 * world coordinates with no per-frame matrix gymnastics.
 *
 * Coordinate convention:
 *   - Camera at origin looking down -Z.
 *   - Video plane lives at z = 0 with x in [-W/2, W/2] and y in [-H/2, H/2]
 *     in *world units*, matching the canvas dimensions in pixels. So a
 *     landmark at (lm.x * W - W/2, -lm.y * H + H/2, 0) lines up under
 *     itself when the canvas is overlaid on the video.
 *
 * We deliberately keep this client-only: GLTFLoader and the WebGL
 * renderer pull DOM globals that aren't available during SSR. The
 * consumer must call `LiveARScene.create()` from a useEffect.
 */

import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

const X_AXIS = new THREE.Vector3(1, 0, 0);

export type ARPlacement = {
  /** Centre of the ring on the band, in normalised video coords [0..1]. */
  cx: number;
  cy: number;
  /** Vector along the finger axis (MCP -> PIP) in normalised coords. */
  axisX: number;
  axisY: number;
  /** Optional finger-axis depth component in normalised video-width units. */
  axisZ?: number;
  /**
   * Target ring inner diameter in normalised video-width units. This is
   * not the mesh's outer diameter; the hole has to fit the finger.
   */
  widthHint: number;
  /** Relative z-depth signal (-1..1ish) to fake perspective tilt. Optional. */
  depthZ?: number;
};

export class LiveARScene {
  readonly canvas: HTMLCanvasElement;
  readonly renderer: THREE.WebGLRenderer;
  readonly scene: THREE.Scene;
  readonly camera: THREE.PerspectiveCamera;
  /** Group that owns the loaded ring mesh — transforms apply here. */
  readonly ringGroup: THREE.Group;
  /** Clips the camera-far side of the ring so the rear band does not show through. */
  private readonly rearClipPlane = new THREE.Plane(new THREE.Vector3(0, 0, 1), 0);
  private envTexture: THREE.Texture | null = null;
  private cameraDistance = 1000; // see _fitCamera

  /** Estimated inner ring diameter in mesh coords, used for live fit scale. */
  private meshInnerDiameter = 1;
  /** Estimated outer ring diameter in mesh coords, retained for geometry analysis/debug. */
  private meshOuterDiameter = 1;
  /** Whether a ring has been loaded yet. */
  private hasRing = false;
  /** Cached source bbox size, so we can recompute orientation on cycle. */
  private cachedBoxSize: THREE.Vector3 | null = null;
  /** The loaded ring root, used by orientation cycling. */
  private ringRoot: THREE.Object3D | null = null;
  /** Mesh URL — used as the localStorage key for the user's orientation choice. */
  private meshUrl: string | null = null;
  /** User-selected spin around the ring hole axis, in radians. */
  private orientationSpin = 0;
  /**
   * Orientation step in [0, 11]. Encodes:
   *   axisIdx = step >> 2          (0=X, 1=Y, 2=Z — which bbox axis becomes the band-hole)
   *   spinIdx = step & 3           (0..3 = 0°, 90°, 180°, 270° spin around the band-hole axis)
   * The default (step 0) corresponds to "smallest bbox axis becomes band-hole, no spin"
   * — chosen automatically on load if no localStorage preference exists.
   */
  private orientationStep = 0;
  private viewWidth = 0;
  private viewHeight = 0;

  static create(canvas: HTMLCanvasElement): LiveARScene {
    return new LiveARScene(canvas);
  }

  private constructor(canvas: HTMLCanvasElement) {
    this.canvas = canvas;
    this.renderer = new THREE.WebGLRenderer({
      canvas,
      antialias: true,
      alpha: true,
      premultipliedAlpha: false,
    });
    this.renderer.setPixelRatio(Math.min(2, window.devicePixelRatio || 1));
    this.renderer.setClearColor(0x000000, 0);
    this.renderer.toneMapping = THREE.ACESFilmicToneMapping;
    this.renderer.toneMappingExposure = 1.05;
    this.renderer.localClippingEnabled = true;

    this.scene = new THREE.Scene();

    // PerspectiveCamera with a tight FOV — wider FOVs distort the ring
    // near the edges of the video. 24 deg + matching distance gives an
    // effectively pseudo-orthographic projection within the central crop
    // where the hand actually sits.
    this.camera = new THREE.PerspectiveCamera(24, 1, 1, 5000);
    this.camera.position.set(0, 0, this.cameraDistance);
    this.camera.lookAt(0, 0, 0);

    // Studio-ish indoor environment for PBR metal reflections, without
    // pulling a 1 MB external HDR. RoomEnvironment is built into three.
    const pmrem = new THREE.PMREMGenerator(this.renderer);
    this.envTexture = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    this.scene.environment = this.envTexture;

    // Soft fill lights for definition on top of the env map. Two
    // directional lights covering classic studio key + fill positions.
    const key = new THREE.DirectionalLight(0xffffff, 1.4);
    key.position.set(2, 3, 4);
    this.scene.add(key);
    const fill = new THREE.DirectionalLight(0xffffff, 0.5);
    fill.position.set(-3, -1, 2);
    this.scene.add(fill);
    this.scene.add(new THREE.AmbientLight(0xffffff, 0.25));

    this.ringGroup = new THREE.Group();
    this.scene.add(this.ringGroup);
  }

  /** Resize renderer + camera frustum to match the visible video dims. */
  resize(width: number, height: number) {
    if (width < 1 || height < 1) return;
    this.viewWidth = width;
    this.viewHeight = height;
    this.renderer.setSize(width, height, false);
    this.camera.aspect = width / height;
    this.camera.updateProjectionMatrix();
    // Compute camera distance so that the camera frustum at z=0 has
    // exactly `height` world units of vertical span. Then world units ==
    // pixels at the video plane and a landmark in pixel coords maps
    // directly to a world position.
    const vFov = (this.camera.fov * Math.PI) / 180;
    this.cameraDistance = height / (2 * Math.tan(vFov / 2));
    this.camera.position.set(0, 0, this.cameraDistance);
    this.camera.lookAt(0, 0, 0);
  }

  matchesVideoSize(width: number, height: number): boolean {
    return this.viewWidth === width && this.viewHeight === height;
  }

  /** Load a textured GLB from a URL. Replaces the previous ring if any.
   *
   * The camera-far side of the ring is clipped by a material plane. This
   * approximates finger occlusion without inserting fake depth geometry,
   * which can incorrectly cut the GLB into disconnected pieces.
   */
  async loadRing(url: string): Promise<void> {
    const loader = new GLTFLoader();
    const gltf = await loader.loadAsync(url);

    // Clear previous ring (if any).
    while (this.ringGroup.children.length > 0) {
      const c = this.ringGroup.children[0];
      this.ringGroup.remove(c);
      disposeNode(c);
    }
    this.ringRoot = null;
    this.meshUrl = url;
    this.ringGroup.rotation.set(0, 0, 0);

    const root = gltf.scene;

    // 1. Centre on bbox origin so transforms pivot at the ring's middle.
    const box = new THREE.Box3().setFromObject(root);
    const size = new THREE.Vector3();
    box.getSize(size);
    const center = new THREE.Vector3();
    box.getCenter(center);
    root.position.sub(center);

    // Cache bbox for the orientation-cycle button (it re-applies axis
    // selection from scratch each press, so it needs the originals).
    this.cachedBoxSize = size.clone();

    // 2. Compute scale references from the actual vertex cloud. Bbox
    // guesses break on generated solitaire rings because the raised stone
    // changes the longest/shortest axes. The correct hole axis is the
    // axis whose perpendicular projection has the largest empty centre.
    root.updateMatrixWorld(true);
    const analysis = analyzeRingGeometry(root, size);
    this.meshOuterDiameter = analysis.outerDiameter;
    this.meshInnerDiameter = analysis.innerDiameter;

    // 3. Force PBR depthWrite/Test and bump envMapIntensity because some
    //    generated outputs ship with a baked low value.
    root.traverse((node) => {
      if ((node as THREE.Mesh).isMesh) {
        const mat = (node as THREE.Mesh).material as THREE.Material;
        for (const m of Array.isArray(mat) ? mat : [mat]) {
          m.depthWrite = true;
          m.depthTest = true;
          m.clippingPlanes = [this.rearClipPlane];
          m.needsUpdate = true;
          if ((m as THREE.MeshStandardMaterial).isMeshStandardMaterial) {
            (m as THREE.MeshStandardMaterial).envMapIntensity = 1.2;
          }
        }
      }
    });

    this.ringGroup.add(root);
    this.ringRoot = root;

    // 4. Pick an initial orientation. If the user has previously dialled
    //    in a step for this exact mesh, restore it; otherwise default to
    //    "smallest bbox axis becomes band-hole, no spin" (step 0..3
    //    depending on which axis is smallest).
    const axisIdx =
      analysis.holeAxis === "x" ? 0 : analysis.holeAxis === "y" ? 1 : 2;
    const remembered = readRememberedOrientation(url);
    this.orientationStep = remembered ?? axisIdx << 2; // spinIdx = 0
    this.applyOrientation();

    this.hasRing = true;
  }

  /**
   * Cycle through all 12 plausible orientations of the ring relative to
   * the finger. The UI exposes this as a single "Rotate" button — the
   * user can keep pressing until the band wraps cleanly and the stone
   * faces up. Persists the chosen step to localStorage keyed by the GLB
   * URL so the user only has to do it once per design.
   */
  cycleOrientation(): void {
    this.orientationStep = (this.orientationStep + 1) % 12;
    this.applyOrientation();
    if (this.meshUrl) writeRememberedOrientation(this.meshUrl, this.orientationStep);
  }

  /** Apply the current orientationStep to the ring root mesh. */
  private applyOrientation(): void {
    if (!this.ringRoot) return;
    const axisIdx = this.orientationStep >> 2; // 0..2
    const spinIdx = this.orientationStep & 3; // 0..3

    // Reset, then rotate so axisIdx (0=X, 1=Y, 2=Z) becomes the band-hole
    // axis (world +X), then spin 90° × spinIdx around that axis.
    this.ringRoot.rotation.set(0, 0, 0);
    if (axisIdx === 1) {
      // +Y → +X (rotate around Z by 90°)
      this.ringRoot.rotation.z = Math.PI / 2;
    } else if (axisIdx === 2) {
      // +Z → +X (rotate around Y by 90°)
      this.ringRoot.rotation.y = Math.PI / 2;
    }
    this.orientationSpin = (spinIdx * Math.PI) / 2;
    this.ringGroup.rotation.x = this.orientationSpin;
  }

  /** Current orientation step, exposed so the UI can show "Rotation 3/12". */
  getOrientationStep(): number {
    return this.orientationStep;
  }

  /** Position/orient the ring group from a per-frame landmark placement. */
  updatePlacement(p: ARPlacement, videoWidth: number, videoHeight: number) {
    if (!this.hasRing) return;

    // Map normalised landmark coords to world (== pixel) coords. Three's
    // +Y is up, MediaPipe's +Y is down — flip.
    const x = p.cx * videoWidth - videoWidth / 2;
    const y = -(p.cy * videoHeight - videoHeight / 2);
    this.ringGroup.position.set(x, y, 0);

    // Finger axis in world coords (Y-flipped, optional Z depth). The
    // mesh's band-hole axis is +X after auto-orientation, so a quaternion
    // gives a cleaner live pose than Euler z-only rotation.
    const ax = p.axisX * videoWidth;
    const ay = -(p.axisY * videoHeight);
    const az = clamp((p.axisZ ?? 0) * videoWidth, -videoWidth * 0.22, videoWidth * 0.22);
    const targetDir = new THREE.Vector3(ax, ay, az);
    if (targetDir.lengthSq() > 0.0001) {
      targetDir.normalize();
      const align = new THREE.Quaternion().setFromUnitVectors(X_AXIS, targetDir);
      const spin = new THREE.Quaternion().setFromAxisAngle(X_AXIS, this.orientationSpin);
      this.ringGroup.quaternion.copy(align).multiply(spin);
    }

    // Scale so the mesh's estimated inner hole fits the finger. Scaling
    // by the outer bbox is what made the ring look too tight and
    // misregistered on the live hand.
    const targetInnerDiameter = Math.max(10, p.widthHint * videoWidth);
    const scale = targetInnerDiameter / this.meshInnerDiameter;
    this.ringGroup.scale.setScalar(scale);

    // Keep the camera-near side of the ring and clip the rear arc. The
    // plane is in world space; camera looks toward -Z, so z values lower
    // than this threshold are the far side. A small negative offset keeps
    // the front setting and visible band shoulders intact.
    const clipZ = -targetInnerDiameter * 0.12;
    this.rearClipPlane.normal.set(0, 0, 1);
    this.rearClipPlane.constant = -clipZ;
  }

  /** Hide the ring (e.g. when no hand is detected). */
  setVisible(visible: boolean) {
    this.ringGroup.visible = visible;
  }

  render() {
    this.renderer.render(this.scene, this.camera);
  }

  /** Free GPU + WebGL resources. */
  dispose() {
    while (this.ringGroup.children.length > 0) {
      const c = this.ringGroup.children[0];
      this.ringGroup.remove(c);
      disposeNode(c);
    }
    if (this.envTexture) {
      this.envTexture.dispose();
      this.envTexture = null;
    }
    this.renderer.dispose();
  }
}

function disposeNode(node: THREE.Object3D) {
  node.traverse((child) => {
    const m = child as THREE.Mesh;
    if (m.isMesh) {
      m.geometry?.dispose?.();
      const mat = m.material;
      if (Array.isArray(mat)) mat.forEach((mm) => mm.dispose?.());
      else mat?.dispose?.();
    }
  });
}

function clamp(v: number, lo: number, hi: number) {
  return v < lo ? lo : v > hi ? hi : v;
}

type AxisName = "x" | "y" | "z";

type RingGeometryAnalysis = {
  holeAxis: AxisName;
  innerDiameter: number;
  outerDiameter: number;
};

function analyzeRingGeometry(root: THREE.Object3D, size: THREE.Vector3): RingGeometryAnalysis {
  const points = collectMeshPoints(root);
  const sortedAsc = [size.x, size.y, size.z].sort((a, b) => a - b);
  const bboxOuter = sortedAsc[1] || sortedAsc[0] || 1;
  const bboxFallback: RingGeometryAnalysis = {
    holeAxis: shortestAxis(size),
    innerDiameter: Math.max(bboxOuter * 0.78, 0.001),
    outerDiameter: bboxOuter,
  };
  if (points.length < 96) return bboxFallback;

  const candidates = (["x", "y", "z"] as const).map((axis) => {
    const radii = points
      .map((p) => radialDistance(p, axis))
      .filter((v) => Number.isFinite(v) && v > 0)
      .sort((a, b) => a - b);
    if (radii.length < 96) {
      return { axis, score: 0, inner: bboxFallback.innerDiameter / 2, outer: bboxOuter / 2 };
    }
    const inner = percentile(radii, 0.06);
    const outer = percentile(radii, 0.94);
    const score = outer > 0 ? inner / outer : 0;
    return { axis, score, inner, outer };
  });

  const best = candidates.reduce((a, b) => (b.score > a.score ? b : a));
  if (!Number.isFinite(best.score) || best.score < 0.22) return bboxFallback;

  const outerDiameter = Math.max(best.outer * 2, bboxOuter * 0.65, 0.001);
  const innerDiameter = clamp(best.inner * 2 * 0.98, outerDiameter * 0.62, outerDiameter * 0.9);
  return {
    holeAxis: best.axis,
    innerDiameter,
    outerDiameter,
  };
}

function collectMeshPoints(root: THREE.Object3D): THREE.Vector3[] {
  const points: THREE.Vector3[] = [];
  const temp = new THREE.Vector3();
  root.traverse((node) => {
    const mesh = node as THREE.Mesh;
    const pos = mesh.isMesh
      ? (mesh.geometry?.attributes?.position as THREE.BufferAttribute | undefined)
      : undefined;
    if (!pos) return;
    const stride = Math.max(1, Math.floor(pos.count / 2500));
    for (let i = 0; i < pos.count; i += stride) {
      temp.fromBufferAttribute(pos, i).applyMatrix4(mesh.matrixWorld);
      points.push(temp.clone());
    }
  });
  return points;
}

function radialDistance(p: THREE.Vector3, axis: AxisName): number {
  if (axis === "x") return Math.hypot(p.y, p.z);
  if (axis === "y") return Math.hypot(p.x, p.z);
  return Math.hypot(p.x, p.y);
}

function percentile(sorted: number[], q: number): number {
  if (sorted.length === 0) return Number.NaN;
  const idx = clamp(Math.floor((sorted.length - 1) * q), 0, sorted.length - 1);
  return sorted[idx];
}

function shortestAxis(size: THREE.Vector3): AxisName {
  if (size.x <= size.y && size.x <= size.z) return "x";
  if (size.y <= size.z) return "y";
  return "z";
}

// ---- localStorage: remember the orientation choice per mesh ----
// Keyed by mesh URL so the same design always loads at the user's
// preferred orientation, while new designs get the default auto-pick.

const ORIENTATION_STORE_KEY = "hm.tryon.ring-orientation.v2";

function readRememberedOrientation(meshUrl: string): number | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(ORIENTATION_STORE_KEY);
    if (!raw) return null;
    const map = JSON.parse(raw) as Record<string, number>;
    const v = map[meshUrl];
    return typeof v === "number" && v >= 0 && v < 12 ? v : null;
  } catch {
    return null;
  }
}

function writeRememberedOrientation(meshUrl: string, step: number): void {
  if (typeof window === "undefined") return;
  try {
    const raw = window.localStorage.getItem(ORIENTATION_STORE_KEY);
    const map = raw ? (JSON.parse(raw) as Record<string, number>) : {};
    map[meshUrl] = step;
    window.localStorage.setItem(ORIENTATION_STORE_KEY, JSON.stringify(map));
  } catch {
    /* quota / privacy mode — silently ignore */
  }
}
